### ISSUE TITLE
Opinion: I found the Getting Started instructions confusing

### ISSUE THREAD

**Issue by Thomas-Sciaroni** [ocaml-dune/binary-distribution#106]
I just installed dune from https://preview.dune.build

I named my project `hello_world_dune` instead of `hello_world` and then it took me a minute to figure out that the final command now had to be `dune exec hello_world_dune`.

If I didn't know something about ocaml already I would not have known which files to open to look for the possible arguments to `dune exec`.

It wasn't obvious to me that the argument to `dune init proj` would become the name of the thing to exec. I had assumed `hello_world` on the final line was the name of the default executable no matter what.

Personally, I think this would be clearer if the instructions were something like:
```sh
$ PROJECT=hello_world
$ dune init proj "$PROJECT"
$ cd "$PROJECT"
$ dune pkg lock
$ dune exec "$PROJECT"
```
It makes it clear that there is a dependency between one instruction and the next.

**Comment by maiste** [comment]
Thanks for opening the issue and the suggestion! I like the solution for the "Getting Started" as t something we expect people to run these instructions the first time they try the preview and have no experience with Dune.
