### ISSUE TITLE
Downloading the developer preview is slow

### ISSUE THREAD

**Issue by gridbugs** [ocaml-dune/binary-distribution#69]
It takes me about 16 seconds to install the developer preview using `curl -fsSL https://get.dune.build/install | bash`. I thought it might be my Australian internet so I set up an alternate version of the script that downloads a tarball that I uploaded to github to compare the speed:
```
 time curl -fsSL https://github.com/gridbugs/dune-binary-distribution/raw/refs/heads/external-env-files-test/install | bash
######################################################################## 100.0%
dune x86_64-unknown-linux-musl was installed successfully to ~/.dune/bin/dune

Sourced "$HOME/.dune/env/env.bash" in "~/.bashrc"

To get started, run:

  source /home/s/.bashrc
  dune --help

real    0m2.432s
user    0m0.358s
sys     0m0.162s
```

That took about 2.5 seconds.

**Comment by Leonidas-from-XIV** [comment]
I assume this is CDN vs no CDN (thus forcing your connection to go to the datacenter in France). I think it would be nice to have `get.dune.build` served through some CDN since we will need that for the fast-opam-repo init as well.

I believe Scaleway also seems to be offering that, we should look into it.

**Comment by gridbugs** [comment]
Is the reason we don't just host it on github so that we can count the number of downloads? If so, what about counting downloads of the install script instead and pointing the install script at tarballs hosted on github?

**Comment by maiste** [comment]
The other reasons are:
- We can't use released because hosting "random binaries" might be against GitHub policy.
- We can't stay with artefacts as the retention date is short.
- We can't use LFS because it is against GitHub policy.

The best solution would be to use a CDN, but it needs to be on top of our website. We need to check with infrastructure people if this is doable.

**Comment by Leonidas-from-XIV** [comment]
@maiste Could you talk to the infrastructure people next week? Speeding up static downloads is one of the things that would make a big difference at a very low engineering cost. Given we expect a non-trivial amount of users from outside of Europe having the most recent couple of files available from a geographically close location will give a much better initial impression.

**Comment by maiste** [comment]
Do you have any metrics from your different locations? Also, what do we define as slow or fast in our case?

**Comment by Leonidas-from-XIV** [comment]
1. @gridbugs metric: 16s to download 6.5MB from our server vs 2.5s from Github so something like 0.4MB/s and and 2.6 MB/s respectively in Australia
2. My metric: 5.5MB/s from our server and 30.8 MB/s from Github in Denmark

**Comment by mtelvers** [comment]
Have you seen the GitHub release download counter?  https://tooomm.github.io/github-release-stats 

e.g. https://tooomm.github.io/github-release-stats/?username=ocaml&repository=opam

**Comment by mtelvers** [comment]
From https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

> Each file included in a release must be under 2 GiB. There is no limit on the total size of a release, nor bandwidth usage.

**Comment by maiste** [comment]
For the opam snapshot we use to speed up the first install, we have the following stats:
https://tooomm.github.io/github-release-stats/?username=ocaml-dune&repository=opam-repository-snapshots

As you can see, none of our files is over 2GiB.

**Comment by Leonidas-from-XIV** [comment]
Oh, this is definitely very cool, I did not know where was a way to see the download count of the releases!

What I don't know about GitHub releases is whether what we are doing is conforming to the ToS of Github. e.g. https://github.com/ocaml-dune/opam-repository-snapshots/releases/tag/opam-repository-d910b0617a51ea90e4547db13a509962fc504f70 is not a release of the software in the git repo, in fact the repo itself is empty.

Likewise, the preview builds we are doing in this repository are not really releases, they are custom builds of a different repo (`ocaml/dune`). Thus while we are definitely within the size limits, I am not sure whether GitHub would shut us for abusing Github releases as a file storage.

**Comment by gridbugs** [comment]
This is now resolved.
