### ISSUE TITLE
Prettyprint `metadata.json`

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml-dune/binary-distribution#94]
Currently the commit diffs by sandworm look rather ugly because `metadata.json` is basically one long file: https://github.com/ocaml-dune/binary-distribution/commit/187790984e201942c248dc371f12b811edc46260

It would be nice to prettyprint it somewhat so a new release would lead to a nicer diff where it is easier to see what has changed.

**Comment by maiste** [comment]
The purpose was to be fast and remove extra useless variables, but as we load it once and have it in memory, it can be nice to be able to read indeed.
