### ISSUE TITLE
Failed to download dune tar

### ISSUE THREAD

**Issue by maiste** [ocaml-dune/binary-distribution#98]
Repost from [#11018](https://github.com/ocaml/dune/issues/11018) by @nojaf

## Expected Behavior

`curl -fsSL https://get.dune.build/install | sh` downloads dune and other magic.

## Actual Behavior

```
curl: (22) The requested URL returned error: 404

error: Failed to download dune tar from "https://get.dune.build/2024-10-17/x86_64-unknown-linux-musl/dune-2024-10-17-x86_64-unknown-linux-musl.tar.gz"
```

## Reproduction

I was trying this in Gitpod, but I'm assuming this is a larger issue.

1. Optional, open new gitpod or devcontainer
1. `curl -fsSL https://get.dune.build/install | sh`

## Specifications

- Version of `dune` (output of `dune --version`):
- Version of `ocaml` (output of `ocamlc --version`)
- Operating system (distribution and version):

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

## Additional information 

Please add some CI so this works very day going forward.

**Comment by maiste** [comment]
@nojaf the script should work again now :+1:

**Comment by nojaf** [comment]
@maiste thanks for the quick reaction! This worked now!
